# Generated by Django 3.1.1 on 2020-09-25 11:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(default=None, max_length=14, unique=True)),
                ('pub_date', models.CharField(default=None, max_length=10)),
                ('order_status', models.CharField(choices=[('1', 'Nowe'), ('2', 'W przygotowaniu'), ('3', 'Wysłane'), ('4', 'Zakończone'), ('5', 'Anulowane')], default=('1', 'Nowe'), max_length=1)),
                ('image', models.CharField(default='?', max_length=20)),
                ('divided', models.CharField(default='?', max_length=8)),
                ('tracking_number', models.CharField(default='?', max_length=22)),
                ('owner', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
            ],
        ),
        migrations.CreateModel(
            name='ArchiveThread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(default=None, max_length=14)),
            ],
        ),
        migrations.CreateModel(
            name='MessagesThread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(default=None, max_length=14)),
                ('creator', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='creator', to='auth.group')),
                ('reciever', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='reciever', to='auth.group')),
            ],
        ),
        migrations.CreateModel(
            name='UnactiveOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(default=None, max_length=14, unique=True)),
                ('pub_date', models.CharField(default=None, max_length=10)),
                ('unactivation_date', models.CharField(default='25.09.20', max_length=10, verbose_name='date_deleted')),
                ('order_status', models.CharField(default='4', max_length=1)),
                ('image', models.CharField(default='?', max_length=20)),
                ('owner', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
            ],
        ),
        migrations.CreateModel(
            name='OrderStatusChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(default='09:03 25.09.20', max_length=16, verbose_name='date')),
                ('change_owner', models.CharField(default=None, max_length=20)),
                ('previous_state', models.CharField(choices=[('1', 'Nowe'), ('2', 'W przygotowaniu'), ('3', 'Wysłane'), ('4', 'Zakończone'), ('5', 'Anulowane')], default=None, max_length=1)),
                ('new_state', models.CharField(choices=[('1', 'Nowe'), ('2', 'W przygotowaniu'), ('3', 'Wysłane'), ('4', 'Zakończone'), ('5', 'Anulowane')], default=None, max_length=1)),
                ('order', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='page.activeorder')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thread', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='page.messagesthread')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_op', models.CharField(default=None, max_length=20)),
                ('message_text', models.CharField(default=None, max_length=200)),
                ('message_date', models.CharField(default='09:03 25.09.20', max_length=16, verbose_name='date')),
                ('thread', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='page.messagesthread')),
            ],
        ),
        migrations.CreateModel(
            name='ArchiveMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_op', models.CharField(default=None, max_length=20)),
                ('message_text', models.CharField(default=None, max_length=200)),
                ('message_date', models.CharField(default='09:03 25.09.20', max_length=16, verbose_name='date')),
                ('thread', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='page.archivethread')),
            ],
        ),
    ]
