# Generated by Django 3.1.1 on 2020-09-14 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('n', 'not recieved'), ('r', 'recieved'), ('p', 'in preparation'), ('f', 'finished'), ('s', 'send')], default=('n', 'not recieved'), max_length=1),
        ),
    ]
