# Generated by Django 3.1.1 on 2020-09-14 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_order_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[(0, 'not recieved'), (1, 'recieved'), (2, 'in preparation'), (3, 'finished'), (4, 'send')], default=(0, 'not recieved'), max_length=1),
        ),
    ]
