# Generated by Django 3.1.1 on 2020-09-14 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0003_auto_20200914_1016'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=20)),
                ('pub_date', models.DateTimeField(verbose_name='date pubilshed')),
                ('order_status', models.CharField(choices=[('1', 'not recieved'), ('2', 'recieved'), ('3', 'in preparation'), ('4', 'finished'), ('5', 'send'), ('6', 'done')], default=('1', 'not recieved'), max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='UnactiveOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=20)),
                ('pub_date', models.DateTimeField(verbose_name='date pubilshed')),
                ('unactivation_date', models.DateTimeField(verbose_name='date_deleted')),
                ('order_status', models.CharField(default='6', max_length=1)),
            ],
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
